/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tomass1996.MCPwdRecovery;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.swing.ImageIcon;

/**
 *
 * @author Farr Family
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDetails = new javax.swing.JPanel();
        tfUsr = new javax.swing.JTextField();
        tfPwd = new javax.swing.JTextField();
        bnDecipher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MC Pwd Recovery");
        setIconImage((new ImageIcon(MainFrame.class.getResource("Icon.png")).getImage()));

        pnDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        tfUsr.setEditable(false);

        tfPwd.setEditable(false);

        javax.swing.GroupLayout pnDetailsLayout = new javax.swing.GroupLayout(pnDetails);
        pnDetails.setLayout(pnDetailsLayout);
        pnDetailsLayout.setHorizontalGroup(
            pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfUsr)
            .addComponent(tfPwd)
        );
        pnDetailsLayout.setVerticalGroup(
            pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailsLayout.createSequentialGroup()
                .addComponent(tfUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bnDecipher.setText("Recover");
        bnDecipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDecipherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bnDecipher, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnDecipher))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnDecipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDecipherActionPerformed
        try {
            File lastlogin = new File(Util.getAppDir("minecraft"), "lastlogin");
            Cipher cipher = Util.getCipher(Cipher.DECRYPT_MODE, "passwordfile");
            String[] usrpwd = Util.readUserPwd(lastlogin, cipher);
            this.tfUsr.setText(usrpwd[0]);
            this.tfPwd.setText(usrpwd[1]);
            usrpwd = null;
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bnDecipherActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bnDecipher;
    public javax.swing.JPanel pnDetails;
    public javax.swing.JTextField tfPwd;
    public javax.swing.JTextField tfUsr;
    // End of variables declaration//GEN-END:variables
}
